### ISSUE TITLE
[hlx up] provide an option to simulate a domain with `--host`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#108]
for config like the content git and directory index, it would be required for hlx up to take a `--strain` argument. defaults to `default` :-)

**Comment by trieloff** [comment]
Sounds reasonable. I've been thinking of introducing a `development` strain, but making it an argument to `hlx up` is better.

**Comment by filmaj** [comment]
What about the situation where multiple strains are defined, mapping different URLs to different content repos? Is that outside the scope of this conversation?

**Comment by tripodsan** [comment]
another idea from @kptdobe is to introduce _environments_. the config would allow to define environment specific variables. eg:

**helix-config.yaml**
```
environments:
  local-dev:
    hostname: localhost:3000
  production:
    hostname: www.project-helix.io
  staging:
    hostname: stage.project-helix.io

strains:
  default:
    url: https://${ENV.hostname}/
```

and then run for example:

```
hlx up --env=local-dev
```

or

```
hlx publish --env=staging
```

btw: this is just an example syntax. I'm sure there is a better way in YAML to do this.

**Comment by tripodsan** [comment]
regarding the conditionals; we might look at:
- [ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html)
- [AWS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)

**Comment by trieloff** [comment]
I'm not a fan of variable expansion in YAML, especially not anything home-grown.

I prefer @filmaj's suggestion on emulating hostnames like this: `http://localhost:3000/www.project-helix.io`

In addition, we could support something like https://www.npmjs.com/package/dotlocal so that `http://www.project-helix.io.local:3000` would work as well.

**Comment by tripodsan** [comment]
at some point we need to have an posibility to select different environments. or how else could we leverage the same config for production and staging? you probably don't want to copy past an entire config and just rename the domain?

**Comment by trieloff** [comment]
```yaml
strains:
  production: &production
    code: …
    content: …
    url: https://www.example.com
    otherconfig: …
  staging:
    <<: &production #inherit everything from production
    code: … # but override this
    url: https://staging.example.com # and this
  
```

**Comment by trieloff** [comment]
Yes, you will end up with lots and lots of strains (lots of content sources times two for two publishing stages), but I don't think that the environments proposal is going to make life easier:

1. it isn't intuitive which conditions work on strains and which work on environments
2. it isn't intuitive how configurations merge when there are conflicts between strains and environments
3. it is reducing the uniformity of the configuration format, making it harder to reason about, and easier to introduce bugs.

With the proposal in adobe/helix-shared#20 you can create re-usable conditions like this:

```yaml
definitions:
  production-env:
    hostname=: www.project-helix.io
  staging-env:
    hostname=: stage.project-helix.io

strains:
  default:
    conditions:
      and:
        *production-env
        path: /
  default-stage:
    conditions:
      and:
        *staging-env
        path: /

  docs:
    conditions:
      and:
        *production-env
        path: /docs
  docs-stage:
    conditions:
      and:
        *staging-env
        path: /docs
```
