### ISSUE TITLE
Strains: review concept

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#118]
I am working now with a Fastly service which hosts 2 sites (helpx and adobeio) and the gymnastique around the strains is completely non logical and error prone.

Here is the essential part of the `strains.yaml`:

```
- strain:
    name: adobeio
    code: /acapt/default/https---github-com-kptdobe-adobeio-helix-git--master--
    condition: req.http.host == "adobeio.helix-demo.xyz"
    content:
      repo: adobeio-helix
      ref: master
      owner: kptdobe
- strain:
    name: helpx
    code: /acapt/default/https---github-com-adobe-helix-helpx--master--
    condition: req.http.host == "helpx.helix-demo.xyz"
    content:
      repo: reactor-user-docs
      ref: master
      owner: Adobe-Marketing-Cloud
```

Some facts:
1. in both code bases, I have to edit a `strains.yaml` which contains the definition for my 2 sites. Both sites are completely independent, they only share the same domain / service. Might be an edge case I convey but still, it could be easier and each "site" would contain its own definition.
2. file is in `.hlx` that I sometimes remove because Petridish break the source. I have to restore that file and if I forget before running `hlx strain`, I break all my sites (not only the current one...).
3. I do not commit that file because I assume `.hlx` is a working folder
4. When I run `hlx deploy` a new strain is generated for me but I do not want it, I do not use it! Once the conditions are set, I have a direct access to my site, no need for more. And if I want to test my site with a different content or code, I can create a new condition (like `condition: req.http.host == "helpx-v2.helix-demo.xyz"`).

**Comment by kptdobe** [comment]
Ideally, `helix-config.yaml` I just define:
```
- strain:
    name: helpx
    code: /acapt/default/https---github-com-adobe-helix-helpx--master--
    condition: req.http.host == "helpx.helix-demo.xyz"
    content:
      repo: reactor-user-docs
      ref: master
      owner: Adobe-Marketing-Cloud
- strain:
    name: helpx-v2
    code: /acapt/default/https---github-com-adobe-helix-helpx--v2--
    condition: req.http.host == "helpx-v2.helix-demo.xyz"
    content:
      repo: reactor-user-docs
      ref: master
      owner: Adobe-Marketing-Cloud
```
