### ISSUE TITLE
Support for specifying developer options

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#14]
See better options mentioned here: https://github.com/adobe/helix-cli/issues/14#issuecomment-457049862

---
<del>with more and more options to configure the various commands, it might make sense to support reading the options and flags from a config file.</del>

### <del>suggest:</del>

<del>use the `helix-config.yaml` and add the configuration options:</del>

<del>example</del>

```yaml
contentRepo: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs

loglevel: info
build:
  - target: .hlx/build
  - files: src/*.htl
  - cache: true
  - minify: false

server:
  # ??? move this here?
  contentRepo: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs
  port: 3000,
  browser: false
  
deploy:
  auto: false,
  apikey: ${WSK_AUTH}
  apihost: runtime.adobe.io
  namepsace: ${WSK_NAMESPACE}
  loghost: example.loggly.com
  logkey: ${HLX_LOGKEY}
  target: .hlx/build # maybe reuse build.target
  docker: nodejs8:latest
  default:
    flags: 'green'
```
