### ISSUE TITLE
Lighthouse Score tuning bench for developers

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-cli#1536]
Trying improve the lighthouse score is a very common task for front-end and full-stack web developers.

Tools like https://web.dev/measure/ and documentation like https://web.dev/vitals/ are helpful, but one of the biggest issues in practice is that it is almost impossible to quickly and reliably iterate variations as a developer and get stable and reliable results, especially as a lot of the web vitals are not exactly simple to understand and apply to real-life projects.

During local development usually the built-in chrome tooling (https://developers.google.com/web/tools/lighthouse) is ideal as it let's you run a report on your current state of development.

With helix in particular (and probably any other local development stack that relies on outside network resources) it is extremely hard to find out if smaller changes have a positive or a negative effect as the variance (jitter) between multi subsequent tests to the same page/config vary in a range of about 10 points.

My intuitive assertion is that most of the variance comes from uneven network traffic and a completely static copy of a site and all its resources served from localhost would exhibit no variance between runs.

To be able to determine if a change has a positive or a negative impact it would be great to get very stable measurements between runs. 

So in an ideal world a helix developer could run the lighthouse tooling in chrome subsequently against their helix page (possibly in a special "lighthouse cache mode") and get stable results, then make changes to their code and reliably see small increases/decreases in lighthouse score progressively in a rapid iterative mode.

**Comment by trieloff** [comment]
With the simulator being notified of source code changes, we could automatically run lighthouse tests against all HTML URLs that have been opened in the simulator in the current session. 

For each page, we could then show the current lighthouse score and the trend line of the last few changes.

It doesn't solve the exact same problem, but it helps the developer to reduce cycle time. No more coding, saving, reloading, all you do is save and check the results.

**Comment by davidnuescheler** [comment]
yeah, i don't think that's practical. @trieloff if you want to get some first hand experience, feel free to try to optimize a real-life project.  you might under-estimate the cpu load burden on your local machine to run the lighthouse audit.

also, there are a lot of tools that already produce historic information / trends of lighthouse score including the google search console and of course a number of monitors, but in practice they all show the same. a slow (or sometimes fast) deterioration as the projects grows until someone steps in and cleans things up...

and what we are trying to do is give the person that eventually has to go and clean up the tools to make their live easier through experimentation in code and quick/reliable round trips that indicate if a change helped or not.

**Comment by davidnuescheler** [comment]
to be a little bit more precise, currently comparing the lighthouse score between two subsequent performance run on the default "mobile" setting in chrome i get the following...

<img width="676" alt="Screen Shot 2020-10-08 at 1 24 53 PM" src="https://user-images.githubusercontent.com/5289336/95510427-bbfc7580-096a-11eb-98c0-3394c08eae08.png">
<img width="676" alt="Screen Shot 2020-10-08 at 1 25 19 PM" src="https://user-images.githubusercontent.com/5289336/95510432-be5ecf80-096a-11eb-878b-0985f20c548a.png">

which is a pretty big initial jitter.
digging a little bit deeper into the LCP that is a big contributor to the overall score we see the following in the trace...

<img width="1381" alt="Screen Shot 2020-10-08 at 1 28 35 PM" src="https://user-images.githubusercontent.com/5289336/95510552-f9f99980-096a-11eb-84ea-f7bfbfa3b6f8.png">
<img width="1381" alt="Screen Shot 2020-10-08 at 1 29 52 PM" src="https://user-images.githubusercontent.com/5289336/95510561-fe25b700-096a-11eb-8ad0-a92dbb6438c8.png">
which show the LCP at 2720ms vs. 3003ms respectively, which is still a very big variance...

for this to be useful for smaller optimizations we need to get the overall score variance to 0 and i think the LCP variance to less than 10ms.

**Comment by koraa** [comment]
In order to be properly able to investigate this, I wrote a little tool to
quantify dispersion of performance ratings, I created a tool to repeatedly
run lighthouse and analyse the reports:

https://github.com/koraa/helix-harmonicabsorber

The tool currently:

* Repeatedly runs the lighthouse performance analysis
* Has a module to preform some statistical analyses on the data generated;
  quantifying dispersion and ranking tests by correlation strength with the
  final performance score.

I executed the tool on:

* A live version of the illustrator landing page
* The helix pages simulator hosted version
* A "frozen" version (that is static pages generated with the simulator

In order to create a baseline value I run lighthouse against an empty
website loading no external resources and with just some text as content.
This yielded a performance score of 100.

Visualization of the performance scores:

![gnu](https://user-images.githubusercontent.com/1451261/95910218-01240b80-0da0-11eb-9625-e1efeb908b6b.png)

The image shows 100 hundred samples taken for each of the test cases. We can
see:

* Performance scores for static version and live versions are roughly similar,
  with static version being slightly better.
* Dispersion is in all cases relatively minor, and is the greatest in the simulated
  version (as we would expect)
* An outlier among simulator test results (which I will tread as an outlier)
* There is a startup-improvement in scores for static & live variants but no improvement
  for helix pages variant.

We would expect a slight startup improvement. The fact that the simulated
variant does not show a startup improvement might be an artifact. (Need to
repeat tests). In any case we should be able to circumvent this problem by
discarding the first test result.

The following command can be used to analyze the performance measurements:

```sh
$ node index.js analyze 2020-10-13-simulator | jq '.perf|del(.val)' | json2yaml
```

Simulator performance measurements analysis (outlier excluded):

```yaml
min: 0.37
max: 0.4
range: 0.030000000000000027
mean: 0.3789000000000001
median: 0.38
meansqerr: 2.979000000000007e-05
variance: 2.979000000000007e-05
stdev: 0.005458021619598082
skewness: 0.3052871467099165
```

Live page:

```yaml
min: 0.58
max: 0.66
range: 0.08000000000000007
mean: 0.6475999999999992
median: 0.65
meansqerr: 6.424000000000008e-05
variance: 6.424000000000008e-05
stdev: 0.008014985963805557
skewness: -6.066717740221321
```

Static  version:

```yaml
min: 0.64
max: 0.67
range: 0.030000000000000027
mean: 0.6586999999999985
median: 0.66
meansqerr: 1.531000000000004e-05
variance: 1.531000000000004e-05
stdev: 0.003912799509302776
skewness: -2.1382870292822957
```

No great difference in the amount of jitter can be seen in these numbers, but
the graph for the simulator looks a bit more jittery indeed.
I'll re run the measurements and I'll re run analysis with startup measurements
rejected. I suspect that this will indeed show (numerically as well) that statifying
the website has achieved a slight reduction in jitter over the simulator version; but
not by much.

I will also test with the rest of the resources referenced in the html hosted locally
and with a socks proxy caching ALL the resources (even ones referenced from JS).

---

Ranking the correlation coefficients (spearman's rho):

```sh
node index.js analyze 2020-10-13-online | jq '.ranks.score_spearman_rho[][]' -r | while read a; read b; do echo "$b $a"; done | head -n 10
```

Online version:

```sh
0.9258571463621273 total-blocking-time
0.45000772128568967 first-cpu-idle
0.45000772128568967 bootup-time
0.4477458820532666 interactive
0.38111973808700605 mainthread-work-breakdown
0.3623592686971113 third-party-summary
-0.3367292021701153 offscreen-images
0.23931523276157138 first-contentful-paint
0.23931523276157138 first-meaningful-paint
0.23931523276157138 uses-rel-preload
```

Simulator:

```sh
0.4366066165798841 largest-contentful-paint
0.41019441980876864 interactive
0.3881092343453139 first-contentful-paint
0.3881092343453139 first-meaningful-paint
0.38472849621497596 render-blocking-resources
0.3598369537149266 uses-rel-preload
0.3321649387480108 first-cpu-idle
-0.28762637531363694 unused-javascript
-0.28762637531363694 uses-text-compression
0.26640110410665235 speed-index
```

Static:

```sh
0.5318379456824813 cumulative-layout-shift
0.39702812947256694 total-blocking-time
0.3610589899952383 speed-index
0.3478267798232503 first-cpu-idle
0.3178017502377199 interactive
0.28634895893534756 bootup-time
0.28634895893534756 uses-rel-preconnect
0.28634895893534756 third-party-summary
0.28634895893534756 offscreen-images
0.22182845845012944 uses-webp-images
```

The ranking for the simulator seems to confirm that largest-contentful-paint has the strongest correlation.
I will have to investigate Pearson's rho and raw value correlations some more as both yielded values I could
not explain. The latter probably yielded weird values because of nonlinerarities in how the raw value is mapped
to a score, but that's just a hypothesis.

In general, it would be extremely useful to have more significant digits for the overall performance score as
well as partial scores; we're operating at the limits of what two digits can capture accurately here 
which might be one of the basic issues we're dealing with…

**Comment by koraa** [comment]
# foo

Here are the evaluations of test samples, startup sample discounted, obvious float errors removed:

Static:

```yaml
min: 0.65
max: 0.67
range: 0.02
mean: 0.6588999999999985
median: 0.66
meansqerr: 1.179e-05
variance: 1.179e-05
stdev: 0.0034336569426778847
skewness: -1.7232497144681784
```

Online:

```yaml
min: 0.64
max: 0.66
range: 0.02
mean: 0.6481999999999992
median: 0.65
meansqerr: 1.876e-05
variance: 1.876e-05
stdev: 0.004331281565541547
skewness: -0.8967342505927873
```

Simulator (for reference, startup sample discounted even though sample was not an outlier):

```yaml
min: 0.37
max: 0.4
range: 0.030
mean: 0.3789
median: 0.38
meansqerr: 2.979e-05
variance: 2.979e-05
stdev: 0.005458021619598082
skewness: 0.3052871467099165
```

The results here are more in line with what we would expect; with the outlier startup
sample removed, variance and standard deviation now reflect that there is a slightly
higher jitter in the simulator sample, although the difference is not large.

---

Correlation coefficients; again spearman's rho:

Static:

```sh
0.5163419943678885 cumulative-layout-shift
0.3659357595116861 total-blocking-time
0.3062355925445969 first-cpu-idle
0.2912093270346321 speed-index
0.2710416452569115 interactive
-0.19215993378237461 unused-javascript
0.17374128635782696 uses-webp-images
-0.1415836625726004 uses-http2
0.11447834808379734 largest-contentful-paint
0.08545805893078079 first-contentful-paint
```

Online:

```sh
0.9239772773777101 total-blocking-time
0.3892753917691937 interactive
0.38451230047079843 first-cpu-idle
0.38451230047079843 bootup-time
0.337099931231621 largest-contentful-paint
-0.337099931231621 offscreen-images
0.32415684727701766 mainthread-work-breakdown
-0.3140475528855477 uses-text-compression
0.2751836173319355 third-party-summary
0.21878074407696788 unused-javascript
```

Simulator:

```sh
0.454198523525403 largest-contentful-paint
0.4228415633315904 interactive
0.38977615167187374 first-contentful-paint
0.38977615167187374 first-meaningful-paint
0.38520950283845395 render-blocking-resources
0.3598369537149266 uses-rel-preload
0.3358067139141884 first-cpu-idle
-0.2901353105846082 unused-javascript
-0.2901353105846082 uses-text-compression
0.2677895154933008 speed-index
```

No change is visible in the correlation coefficients with startup samples rejected.

**Comment by koraa** [comment]
Repeat data collection…

Startup values now look very weird. There is an obvious outlier in the
simulator data again, but this time it's the very first sample. The data below
besides the image is with startup samples removed. I wonder if increased
latency somehow affects the score in some non trivial way? Maybe these extreme
outliers are examples of the simulator encountering errors? Maybe whatever
error page it shows performs better than the actual page?

The performance scores & analysis look as expected, the correlations are a bit different.
Let's see how things behave with even less network impact…

![gnu2](https://user-images.githubusercontent.com/1451261/95989349-71776f00-0e2a-11eb-98c2-22e43967b0c1.png)

Online:

```yaml
min: 0.63
max: 0.66
range: 0.030000000000000027
mean: 0.6413000000000002
median: 0.64
meansqerr: 1.731000000000006e-05
variance: 1.731000000000006e-05
stdev: 0.0041605288125429515
skewness: 2.503431267889871
```

Static:

```yaml
min: 0.65
max: 0.67
range: 0.020000000000000018
mean: 0.6582999999999986
median: 0.66
meansqerr: 1.6110000000000013e-05
variance: 1.6110000000000013e-05
stdev: 0.004013726448077897
skewness: -1.2824705669665608
```

Simulator:

```yaml
min: 0.36
max: 0.4
range: 0.040000000000000036
mean: 0.3779
median: 0.38
meansqerr: 6.25900000000001e-05
variance: 6.25900000000001e-05
stdev: 0.0079113842025274
skewness: 0.6332688975065855
```

Online Correlations:

```sh
0.7090822240613996 cumulative-layout-shift
0.25713986031517866 max-potential-fid
0.23322460790488628 interactive
0.23322460790488628 bootup-time
0.22909760251381434 total-blocking-time
0.19475963626819157 third-party-summary
0.19087132412256771 first-cpu-idle
0.13864615467310568 mainthread-work-breakdown
0.09924764259929114 speed-index
0.07352083616875656 largest-contentful-paint
```

Static Correlations:

```sh
0.5276389488914551 cumulative-layout-shift
0.5111147927369475 largest-contentful-paint
0.47784781535102155 uses-webp-images
0.40087532216573774 total-blocking-time
0.3248657123059835 interactive
0.29755588644912756 first-contentful-paint
0.29755588644912756 first-meaningful-paint
-0.2936508761547175 render-blocking-resources
-0.26371505554526137 uses-http2
0.22051088028436475 unused-javascript
```

Simulator Correlations:

```sh
0.5735388031673083 first-cpu-idle
0.5700859512146451 interactive
0.5660154649643014 render-blocking-resources
0.529133069381913 uses-rel-preload
0.5018591992359485 first-contentful-paint
0.5018591992359485 first-meaningful-paint
-0.4872860450978009 unused-javascript
-0.4872860450978009 uses-text-compression
0.471454801287033 speed-index
0.38025751475228825 uses-http2
```

**Comment by davidnuescheler** [comment]
thanks for the data, very interesting... 
when i read the browser output in the chrome version of the tooling correctly it suggests (at least in the UI) that it would warm up the tests, so my assumption would be that first test / initial sample would already be discarded by the browser. 

however it seems that that variance (range) in my interactive testing is already bigger than what you were able to see in the simulator over 50 tests, which makes me wonder if the comparison to the interactive tool is not very accurate.

i think that in an ideal world we would get to a place where we can stabilize the in browser testing to a point where the first "warmed up?" sample in the browser gives us a result without any jitter. it would be undesirable to have to move the developer to our own benchmark tool chain as the lighthouse score in chrome would be the most intuitive and familiar tool set for a developer.

having said that, i will produce a fork of the respective page for us to run the same tests against.

**Comment by koraa** [comment]
> when i read the browser output in the chrome version of the tooling correctly
> it suggests (at least in the UI) that it would warm up the tests, so my
> assumption would be that first test / initial sample would already be
> discarded by the browser.

I see no evidence for that assumption…a test on my end running lighthouse
against a local http server yielded exactly one request against the URL being
tested from both a test triggered in the browser as well as a test with the
command line tool created by lighthouse. If they where discarding the first
sample they would at least have to perform two requests.

> however it seems that that variance (range) in my interactive testing is
> already bigger than what you were able to see in the simulator over 50 tests,
> which makes me wonder if the comparison to the interactive tool is not very
> accurate.

Again, I see no reason for that assumption; the [lighthouse project
github page](https://github.com/GoogleChrome/lighthouse#using-the-node-cli)
explicitly advertises the node package as a way to run the lighthouse scores.
Internally lighthouse seems to work by accessing the chrome developer console
and extracting the measurements from that…this is the case for the node version
which starts the chrome(ium) browser in the background as well as for the in browser
version which probably just integrates the node project somehow…

I am not at all surprised that jitter measurements differ on both our
setups as jitter will depend on a number of factors including:

* Computer model
* CPU Load
* Temperatur (computer being Throtteled)
* Geographic Location
* Network latency
* Computer usage (my setup being a remote controlled mac doing little else but
  running the tests; yours probably being your development machine)
* The fact that I am running chrome in background mode for my tests…

This is part of the reason why I am going though so much trouble to automate jitter
measurements and use statistics to quantify the jitter; this provides us with a much
more reliable baseline to compare changes in jitter with…

Imagine I was just testing an offline version of the page; or one with a lot of
javascript removed and got the measurements I am seeing now on my machine. I
might conclude that my changes to the html yielded the jitter reduction while
really what I would be seeing is the reduced baseline jitter that exists (for
some unknown reason) on my machine.

In that context I regard the measurements I collected thus far as a confirmation of
your assumption; namely that the simulator introduces extra jitter & a performance
penalty over the online version…the similarity of the statified site measurements
and the online measurements clearly shows that.

My measurements also clearly showed that there is a measurable amount of jitter;
now we can start to create additional measurement setups to try to reduce that jitter.
I fully expect reducing the jitter in the automated testing setup I created will
reduce jitter in your browser based setup as well, give or take some unknown factor.

We could of course try to quantify that factor, but given that we have a way to
establish local baselines it's probably easier for us to just use the local baselines
for now.

> i think that in an ideal world we would get to a place where we can stabilize
> the in browser testing to a point where the first "warmed up?" sample in the
> browser gives us a result without any jitter. it would be undesirable to have
> to move the developer to our own benchmark tool chain as the lighthouse score
> in chrome would be the most intuitive and familiar tool set for a developer.

I don't plan to introduce an alternate lighthouse testing setup; the tool I wrote
merely serves the purpose of quantifying jitter. I plan on precisely quantifying
where all the jitter is coming from and leave deciding how we should act on that
information to someone else :)

**Comment by koraa** [comment]
Btw, comparing your range (~0.08) to mine (~0.04) doesn't seem that big of a difference…a factor of two can easily be explained by slightly different test setups. x50 would have me worried :)

**Comment by koraa** [comment]
https://github.com/GoogleChrome/lighthouse/issues/11570

**Comment by koraa** [comment]
Samples taken with increased lighthouse scoring precision:

![foo](https://user-images.githubusercontent.com/1451261/96299755-ce268580-0ff4-11eb-89ca-6e0d04c448da.png)

With outliers rejected (rejected samples 0, 1 and 62):

![bar](https://user-images.githubusercontent.com/1451261/96299846-f57d5280-0ff4-11eb-84bf-494d15a15893.png)

Online:

```yaml
min: 0.6277741685043454
max: 0.6556934181423613
range: 0.02791924963801584
mean: 0.6431464986636055
median: 0.6431779649059242
meansqerr: 7.2114428252040315e-06
variance: 7.2114428252040315e-06
stdev: 0.0026854129710724255
skewness: -1.053733808708144
```

Static:

```yaml
min: 0.6454564245185892
max: 0.6615863675368509
range: 0.01612994301826165
mean: 0.6540134519524533
median: 0.6548073438170335
meansqerr: 9.112066483157189e-06
variance: 9.112066483157189e-06
stdev: 0.0030186199633536496
skewness: -0.48022385033492443
```

Simulator:

```yaml
min: 0.34726108785812104
max: 0.39324967623857643
range: 0.045988588380455386
mean: 0.3656362339586898
median: 0.3660254523756157
meansqerr: 8.709555960174829e-05
variance: 8.709555960174829e-05
stdev: 0.009332500179573976
skewness: 0.2036851025409195
```
