### ISSUE TITLE
Setting a "content root" leads to invalid content delivery

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#188]
Added the following configuration to the strain.yaml file of https://github.com/kptdobe/kirby_docs project:
```
- strain:
    name: acpdr
    code: >-
      /acapt/default/https---github-com-kptdobe-adobeio-techdoc-helix-git--master--
    url: https://adobeio-tech.helix-demo.xyz/acpdr-content/
    content:
      repo: kirby_docs
      ref: master
      owner: kptdobe
      root: /acpdr/api-specification/markdown/narrative/
```

Hit url: https://adobeio-tech.helix-demo.xyz/acpdr-content/technical_overview/SUMMARY.summary.html

On Chrome and on Safari, the behavior is slighty different but after several reloads, you get the following answer: 
```
Error 500: Internal Server Error StatusCodeError: 404 - {"type":"Buffer","data":[52,48,52,58,32,78,111,116,32,70,111,117,110,100,10]}
```

Debugging the activation of the function shows that computed path of the resource is wrong: 
`https://raw.githubusercontent.com/kptdobe/kirby_docs/master/acpdr/api-specification/markdown/narrative/acpdr-content/technical_overview/SUMMARY.md`

should be: 
`https://raw.githubusercontent.com/kptdobe/kirby_docs/master/acpdr/api-specification/markdown/narrative/technical_overview/SUMMARY.md`

cc @trieloff

**Comment by tripodsan** [comment]
you you basically want to map the directory: `/acpdr/api-specification/markdown/narrative/` in the content repo, below the url: `https://adobeio-tech.helix-demo.xyz/acpdr-content/`

**Comment by tripodsan** [comment]
I tried:

```yaml
- strain:
    name: default
    code: /tripod/default/git-github-com-tripodsan-hlxtest-git--master--
    url: 'https://www.99productrules.com/help'
    content:
      repo: hlxtest
      ref: master
      owner: tripodsan
      root: /docs
```
and it fetches the correct one:
```
$ curl https://www.99productrules.com/help/index.html
```

```
fetching Markdown from https://raw.githubusercontent.com/tripodsan/hlxtest/master/docs/index.md"
```

But it currently gives a 404
