### ISSUE TITLE
Include openwhisk namespace in deployed package coordinates

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#480]
**Is your feature request related to a problem? Please describe.**
When working on a shared project, I realized that the openwhisk namespace where an action is deployed to, is nowhere visible. this also means that all strains actions needs to be on the same namespace.

**Describe the solution you'd like**
the simplest would probably be to add the namespace as prefix to the `package` property of strain, eg:

```yaml
strains:
  default:
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
    package: helix/18b2bd0d91fe90fbf74b857e6946399e3c03262e
```

**Describe alternatives you've considered**
projects needs to use `.env` or other files to coordinate the namespace.
