### ISSUE TITLE
[usability] static value in proposed strain config always localhost

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#496]
**Description**
When trying to deploy a `hlx demo` with an auto-generated config (using `hlx up --save-config`) and after adding a git remote origin, the following error is shown:
```
9864bbcc-1479-4c85-a092-2ece02831241:
  code: https://github.com/<owner>/<repo>.git#<ref>
  content: https://github.com/<owner>/<repo>.git#<ref>
  static: http://localhost/local/default.git/htdocs
```

**Expected behavior**
I guess deploying a Helix project with `static` pointing to the local repository will almost never produce a useful result, because static file delivery will not be possible. A better default suggestion might be to point to the same git repository as specified in `code` instead.

**Version:**
0.13.3-pre1
