### ISSUE TITLE
When deploying, `package` property in 'affected strains' of helix-config gets auto-updated

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#519]
**Description**
Here is the relevant bit of my helix config:

```
strains:
  default:
    <<: *basestrain
    package: 9e81a2d5d82f2a22bf218b446da32414f33c0d87

  launch-docs-helixdemo:
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/launch/docs
    content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
    directoryIndex: README.html
    package: 77017e262a9aa0378abd02c098ecc82e9b6aa7dc

  xd-docs-helixdemo:
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/xd/docs
    content: https://github.com/AdobeXD/plugin-docs.git#master
    directoryIndex: README.html
    package: 77017e262a9aa0378abd02c098ecc82e9b6aa7dc

  starter-docs-helixdemo:
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/starter/docs
    content: https://github.com/AdobeDocs/starter-docs.git#master
    directoryIndex: Overview.html
    package: 77017e262a9aa0378abd02c098ecc82e9b6aa7dc

  helix-demo:
    url: https://adobedevsite.helix-demo.xyz/
    code: ssh://git@github.com/adobe/developer.adobe.com.git#master
    content: ssh://git@github.com/adobe/developer.adobe.com.git#master
    static: https://github.com/adobe/developer.adobe.com.git/htdocs#master
    package: 77017e262a9aa0378abd02c098ecc82e9b6aa7dc
```

When I deploy, the output is:

```
✅  deployment of 7 actions completed:
   - developer-adobe-com/77017e262a9aa0378abd02c098ecc82e9b6aa7dc/default_html (8.31 MiB)
   - developer-adobe-com/77017e262a9aa0378abd02c098ecc82e9b6aa7dc/docs_html (7.33 MiB)
   - developer-adobe-com/77017e262a9aa0378abd02c098ecc82e9b6aa7dc/html (7.14 MiB)
   - developer-adobe-com/77017e262a9aa0378abd02c098ecc82e9b6aa7dc/sitemap_xml (5.47 MiB)
   - developer-adobe-com/77017e262a9aa0378abd02c098ecc82e9b6aa7dc/sitemap_xml.pre (1.77 KiB)
   - developer-adobe-com/hlx--static (1.88 MiB)
   - developer-adobe-com/77017e262a9aa0378abd02c098ecc82e9b6aa7dc/summary_html (7.15 MiB)
Affected strains of ssh://git@github.com/adobe/developer.adobe.com.git#master:
- helix-demo
Updated helix-config.yaml
```

Note that helix seems to identify only the helix-demo strain as being 'affected'. However, in my config, the three strains preceding the helix-demo strain (launch-docs-helixdemo, xd-docs-helixdemo, starter-docs-helixdemo) all follow the same URL pattern as the helix-demo strain. However, their package properties do _not_ get updated.

This was a problem when I recently changed the IO runtime namespace we are running our site on. Because only the helix-demo strain package got updated during deploy, the other strains pointed to non-existent package prefixes (due to the namespace move). So I think the bug here is that helix is not identifying the full set of affected strains.

**Version:**
0.13.3-pre.9

**Comment by tripodsan** [comment]
what is the `code` property of those 3 strains?

during `hlx deploy`, only the strains that match the `code` repository with the current repository are deployed.

changing the namespace w/o redeploying on the respective repos is indeed a problem.
also, you cannot use different namespaces for different strains. see #480

**Comment by filmaj** [comment]
Apologies for delay in response @tripodsan, I'm just coming back from PTO.

Those three strains do not have a `code` property. I guess I should learn what `code` does 😛. Where can I find more information on that?

Different strains + different namespaces won't be a problem for us.

**Comment by tripodsan** [comment]
hmm...i'm sure it is documented somewhere in https://github.com/adobe/helix-shared/pull/12... but probably hard to find.

the `code` property specifies which _code repository_ is used to generate the actions for your strain. during `hlx deploy`, those strains, where the `code` repository matches your current `git origin` will be packaged and deployed to runtime, and it adjusts the `package` property of that strain.

in your example above it seems that only the `helix-demo` has a `code` property that matches your current checkout. the other strains inherit from `basestrain`, so I don't know what the `code` property value is there.

**Comment by filmaj** [comment]
Here's the relevant bits from the top of the `helix-config.yaml`:

```
definitions:
  defaults:
    # Run default content from github repo
    #- &defaultRepo https://github.com/adobe/developer.adobe.com.git#master
    # Run default content from this repo locally
    - &defaultRepo "http://localhost/local/default.git"
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo
      package: 16cd39e4810356ecc384bb5185f081e23cae229b
    proxy:
      &proxystrain
      origin:
        address: 34.227.208.69
        use_ssl: true
        ssl_cert_hostname: www.adobe.io
```
So, ultimately, the `*-docs-helixdemo` strains inherit a `code` property with value `"http://localhost/local/default.git"`
