### ISSUE TITLE
improve local content repository development

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#714]
it should be possible to quickly render content from the local git repository, if it matches the current origin. 

for example:

```
strains:
  - name: default
    content:  https://github.com/adobe/developer.adobe.com.git#master
    code:  https://github.com/adobe/developer.adobe.com.git#master
    static:  https://github.com/adobe/developer.adobe.com.git/htdocs#master
```
When running `hlx up` in a local checkout of `https://github.com/adobe/developer.adobe.com.git`, the content and static content should be served from the local repo instead from github.

Also, it should be possible to disable this feature, or even specify more repositories that should be emulated.

### Suggest

`hlx up` will have a new flag `--git` or `--git-serve` or `--mount` or `--repo` which takes **1** directory argument that must point to a local checkout of a content repository. `hlx up` will then start a git-server on those directory and map all repository references in the strains.

**Comment by tripodsan** [comment]
## Example

1. checkout 2 repositories, `hlxtest` and `hlxtest-content`
2. using this config:
```yaml
definitions:
  repos:
    - &defaultRepo https://github.com/tripodsan/hlxtest.git#master
    - &contentRepo https://github.com/tripodsan/hlxtest-content.git#master

strains:
  - name: api
    url: https://www.99productrules.com/api/general
    code: *defaultRepo
    content: *contentRepo
    static: *defaultRepo

  - name: default
    url: https://www.99productrules.com
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
```
3. start the server like this:
```
$ hlx up --log-level=debug --host=www.99productrules.com --local-repo=. --local-repo=../hlxtest-content
```

now `http://localhost:3000/index.html` is served from the local checkout of `hlxtest` and
`http://localhost:3000/api/general/README.html` is served from the local checkout of `hlxtest-content`: 

```
[hlx] debug: git emulating ssh://git@github.com/tripodsan/hlxtest.git via http://127.0.0.1:52270/helix/github.com--tripodsan--hlxtest.git#master of ./
[hlx] debug: git emulating ssh://git@github.com/tripodsan/hlxtest-content.git via http://127.0.0.1:52270/helix/github.com--tripodsan--hlxtest-content.git#master of ../hlxtest-content
...
[hlx] debug: fetching Markdown from http://127.0.0.1:52270/raw/helix/github.com--tripodsan--hlxtest/master/index.md
...
[hlx] debug: fetching Markdown from http://127.0.0.1:52270/raw/helix/github.com--tripodsan--hlxtest-content/master/README.md
...
```
