### ISSUE TITLE
Cannot resolve path to markdown when using --local-repo and strain with a subdirectory in the `directoryIndex`

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#825]
**Description**
I use `--local-repo` a lot since my internet at home is less than ideal. Recently was reviewing a pull request (https://github.com/adobe/developer.adobe.com/pull/131) which introduces a strain with an external content repo but also uses a subdirectory in its `directoryIndex`. The strain looks like this:

```
  - name: contributor-docs-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/contributor/docs
    content: https://github.com/AdobeDocs/contributor.en.git#master
    directoryIndex: help/introduction.html
    package: developer-adobe-com/633d4dd15734e619449fd1b121d6e97d5a21b6ce
```

Note the `help/` subdirectory in the `directoryIndex`.

The issue I'm having is that the HTML being generated from markdown does not take into account that `help/` subdirectory. So the links fail.

**To Reproduce**
1. Check out the `TocSupport` branch from github.com/adobe/developer.adobe.com
2. `npm install`
3. Clone the https://github.com/AdobeDocs/contributor.en.git repo somewhere.
4. Run `npm start -- --local-repo=.,<path-to-contributor.en-repo> --no-open`
5. Open http://localhost:3000/contributor/docs in your browser
6. Click any of the links in the table of contents on the left.
7. womp womp

**Expected behavior**
Should be able to load the links from the left TOC - looks to be missing `help/` in the path.

**Version:**
1.0.0

**Additional context**
This possibly may also be a problem without using the `--local-repo` flag, I can't verify right now since my internet is _that_ bad at home 😞 (and so I constantly get gateway timeouts from GitHub after 1000msec).

**Comment by tripodsan** [comment]
@filmaj, the `directoryIndex` is a property that is respected during request processing, **not** during HTML generation. the VLC adds the `directoryIndex` value to any request to a _directory_, i.e. a path without extension. 

The problem at hand is, that the resource is internally adjusted to `/help/introduction.html`, but the browser URL remains on `/contributor/docs/`, which causes the problem for all relative links.

If all you content is below `/help`, then it might be better to use `https://github.com/AdobeDocs/contributor.en.git/help#master` as content url.

Another option would be for fastly to use a redirect to the `directoryIndex` adjusted path instead, but some customers would like to keep the `/` nature of the links.

**Comment by tripodsan** [comment]
or you could add a redirect; although I don't know if this is already supported in helix-simulator:

```yaml
  - name: contributor-docs-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/contributor/docs
    content: https://github.com/AdobeDocs/contributor.en.git#master
    directoryIndex: introduction.html
    redirects:
    - from: ^/contributor/docs/+$
      to: /contributor/docs/help/
```
