### ISSUE TITLE
Since helix-cli 2.2.4, proxy strain behaviour has changed, origin property not honoured exactly

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#878]
**Description**
The proxy strain behaviour, at least when running locally, changed between 2.2.1 and 2.2.4 and persists with all versions up to 2.5.0.

Our main 'fallback' proxy strain:

```
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo
    proxy:
      &proxystrain
      origin: https://www.adobe.io/
strains:
  - name: default
    <<: *basestrain
    package: developer-adobe-com/88564b66195f1562ae41fbb395acf8ace49446db

  # === STAGING URLS FOLLOW ===
  # lots of content strains here ommitted
  - name: staging
    <<: *proxystrain
    url: https://adobedevsite.helix-demo.xyz/
```

So, basically, https://adobedevsite.helix-demo.xyz/ gets proxied to https://adobe.io/

With helix-cli 2.2.1, when hitting our adobe.io proxy strain when running locally, helix proxies the request to the `origin` property we have specified in our proxy strain with no modifications:

```
[hlx] info:     __ __    ___
[hlx] info:    / // /__ / (_)_ __
[hlx] info:   / _  / -_) / /\ \ /
[hlx] info:  /_//_/\__/_/_//_\_\ v2.2.1
[hlx] info:
Building project files...done 1727ms
[hlx] info: starting project
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
[hlx] info: Proxy GET request to https://www.adobe.io:443/
```
With helix-cli 2.2.4, however, an `index.html` gets appended to the end of the proxy request - and this is a problem since adobe.io/index.html does not exist:

```
[hlx] info:     __ __    ___
[hlx] info:    / // /__ / (_)_ __
[hlx] info:   / _  / -_) / /\ \ /
[hlx] info:  /_//_/\__/_/_//_\_\ v2.2.4
[hlx] info:
Building project files...done 1627ms
[hlx] info: starting project
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
[hlx] info: Proxy GET request to https://www.adobe.io:443/index.html
```

helix-cli 2.5.0 exhibits the same problem:

```
[hlx] info:     __ __    ___
[hlx] info:    / // /__ / (_)_ __
[hlx] info:   / _  / -_) / /\ \ /
[hlx] info:  /_//_/\__/_/_//_\_\ v2.5.0
[hlx] info:
Building project files...done 2283ms
[hlx] info: starting project
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
[hlx] info: Proxy GET request to https://www.adobe.io:443/index.html
```

**To Reproduce**
1. Clone the `greenkeeper/@adobe/helix-cli-2.5.0` or `greenkeeper/@adobe/helix-cli-2.2.4` branches from https://github.com/adobe/developer.adobe.com
2. `npm install`
3. `npm start`
4. See big error when localhost:3000 loads

**Expected behavior**
The proxy strain to honour what I enter into the `origin` property of my proxy strain _exactly_.

**Screenshots**

**Version:**
2.2.4
2.5.0
