### ISSUE TITLE
deploy sets but does not use defaultRepo variable

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#891]
Follow these steps (loosely based on [getting-started](https://github.com/adobe/helix-home/blob/master/getting-started.md)):
1. `hlx demo demo && cd demo`
2. `hlx build`
3. `git remote add origin <mytestprojectcode_repo_url>.git`
4. `hlx deploy --dirty --add=default`

The resulting `helix-config.yaml` will look like this:
```
#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "<mytestprojectcode_repo_url>.git"

strains:
  - name: default
    code: <mytestprojectcode_repo_url>.git#master
    content: <mytestprojectcode_repo_url>.git#master
    static: <mytestprojectcode_repo_url>.git/htdocs#master
    package: (...)
```
I would expect it to make use of the *defaultRepo variable, since it's being defined above.
