### ISSUE TITLE
publish: confusing console output for local strains

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#892]
If you have a local strain in the `helix-config.yaml`:
```
definitions:
  defaults:
    - & defaultRepo "<mytestprojectcode_repo_url>.git"
    - &localRepo "http://localhost/local/default.git"
strains:
  - name: local
     url: http://localhost:3000/
     code: *localRepo
     content: *localRepo
     static: *localRepo
  - name: default
     url: https://bla.helix-demo.xyz/
     code: *defaultRepo
     content: *defaultRepo
     static: *defaultRepo
```
`hlx publish` will say:
```bash
✅  The following strains have been published and version 56 is now online:
- bla: http://localhost:3000/
- default: https://bla.helix-demo.xyz/

You may now access your site using:
$ curl http://localhost:3000/
```
The last line appears to always display the `url` of the first strain in the list.
