### ISSUE TITLE
[strains.yaml] align configuration options for static content

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#93]
Instead of having `githubStatic`, `s3Static`, etc. we should set the configuration as follows:

```yaml
static:
  type: github
  repo: …
  owner: …
  ref: …
```

this makes the setting more aligned with the rest of `strains.yaml` (all lowercase) and enables an easy lookup of distributors.
